name: Pantheon
version: '1.0.0'
main: dev.goodrich.pantheon.Pantheon
api-version: '1.21'
author: 0xBit
folia-supported: true
description: "Pantheon integrates religion data into Towny's info screens, allowing residents to set their religion and displaying breakdowns in towns and nations."
commands:
  pantheon:
    description: "Pantheon admin command (e.g. /pantheon reload religions)"
    usage: "/pantheon reload religions"
    aliases: [phan]
permissions:
  pantheon.reload:
    description: "Allows reloading of religion configuration."
    default: op
softdepend:
  - Towny